const items = [
  { id: 1, name: "Milk", generalQuality: "Litre", price: 55 },
  { id: 2, name: "Wheat", generalQuality: "Kg", price: 30 },
  { id: 3, name: "Rice", generalQuality: "Kg", price: 40 },
  { id: 4, name: "Oil", generalQuality: "Litre", price: 120 },
  { id: 5, name: "Sugar", generalQuality: "Kg", price: 38 },
  { id: 6, name: "Salt", generalQuality: "Kg", price: 20 },
  { id: 7, name: "Tea", generalQuality: "Kg", price: 450 },
  { id: 8, name: "Coffee", generalQuality: "Kg", price: 600 },
  { id: 9, name: "Butter", generalQuality: "Kg", price: 480 },
  { id: 10, name: "Ghee", generalQuality: "Litre", price: 550 },
  { id: 11, name: "Honey", generalQuality: "Litre", price: 350 },
  { id: 12, name: "Tomato", generalQuality: "Kg", price: 25 },
  { id: 13, name: "Onion", generalQuality: "Kg", price: 30 },
  { id: 14, name: "Potato", generalQuality: "Kg", price: 25 },
  { id: 15, name: "Carrot", generalQuality: "Kg", price: 40 },
  { id: 16, name: "Cabbage", generalQuality: "Kg", price: 30 },
  { id: 17, name: "Cauliflower", generalQuality: "Kg", price: 35 },
  { id: 18, name: "Spinach", generalQuality: "Kg", price: 20 },
  { id: 19, name: "Apple", generalQuality: "Kg", price: 120 },
  { id: 20, name: "Banana", generalQuality: "Kg", price: 40 },
  { id: 21, name: "Mango", generalQuality: "Kg", price: 100 },
  { id: 22, name: "Orange", generalQuality: "Kg", price: 60 },
  { id: 23, name: "Grapes", generalQuality: "Kg", price: 90 },
  { id: 24, name: "Watermelon", generalQuality: "Kg", price: 20 },
  { id: 25, name: "Pineapple", generalQuality: "Kg", price: 70 },
  { id: 26, name: "Papaya", generalQuality: "Kg", price: 30 },
  { id: 27, name: "Chicken", generalQuality: "Kg", price: 250 },
  { id: 28, name: "Mutton", generalQuality: "Kg", price: 600 },
  { id: 29, name: "Fish", generalQuality: "Kg", price: 300 },
  { id: 30, name: "Egg", generalQuality: "Kg", price: 60 },
  { id: 31, name: "Paneer", generalQuality: "Kg", price: 400 },
  { id: 32, name: "Curd", generalQuality: "Litre", price: 50 },
  { id: 33, name: "Juice", generalQuality: "Litre", price: 90 },
  { id: 34, name: "Cold Drink", generalQuality: "Litre", price: 70 },
  { id: 35, name: "Ice Cream", generalQuality: "Kg", price: 200 },
  { id: 36, name: "Bread", generalQuality: "Kg", price: 50 },
  { id: 37, name: "Biscuit", generalQuality: "Kg", price: 120 },
  { id: 38, name: "Noodles", generalQuality: "Kg", price: 150 },
  { id: 39, name: "Pasta", generalQuality: "Kg", price: 140 },
  { id: 40, name: "Flour", generalQuality: "Kg", price: 28 },
  { id: 41, name: "Maida", generalQuality: "Kg", price: 32 },
  { id: 42, name: "Besan", generalQuality: "Kg", price: 60 },
  { id: 43, name: "Dry Fruit Mix", generalQuality: "Kg", price: 850 },
  { id: 44, name: "Cashew", generalQuality: "Kg", price: 1000 },
  { id: 45, name: "Almond", generalQuality: "Kg", price: 950 },
  { id: 46, name: "Raisin", generalQuality: "Kg", price: 600 },
  { id: 47, name: "Pista", generalQuality: "Kg", price: 1100 },
  { id: 48, name: "Dates", generalQuality: "Kg", price: 400 },
  { id: 49, name: "Mustard Oil", generalQuality: "Litre", price: 140 },
  { id: 50, name: "Coconut Oil", generalQuality: "Litre", price: 160 },
  { id: 51, name: "Refined Oil", generalQuality: "Litre", price: 130 },
  { id: 52, name: "Soybean Oil", generalQuality: "Litre", price: 125 },
  { id: 53, name: "Detergent", generalQuality: "Kg", price: 70 },
  { id: 54, name: "Shampoo", generalQuality: "Litre", price: 180 },
  { id: 55, name: "Toothpaste", generalQuality: "Kg", price: 90 },
  { id: 56, name: "Soap", generalQuality: "Kg", price: 60 },
  { id: 57, name: "Hand Wash", generalQuality: "Litre", price: 110 },
  { id: 58, name: "Sanitizer", generalQuality: "Litre", price: 150 },
  { id: 59, name: "Face Wash", generalQuality: "Kg", price: 180 },
  { id: 60, name: "Hair Oil", generalQuality: "Litre", price: 170 },
  { id: 61, name: "Body Lotion", generalQuality: "Litre", price: 220 },
  { id: 62, name: "Cream", generalQuality: "Kg", price: 240 },
  { id: 63, name: "Perfume", generalQuality: "Litre", price: 400 },
  { id: 64, name: "Deodorant", generalQuality: "Litre", price: 300 },
  { id: 65, name: "Shaving Cream", generalQuality: "Kg", price: 100 },
  { id: 66, name: "Razor", generalQuality: "Kg", price: 150 },
  { id: 67, name: "Toilet Cleaner", generalQuality: "Litre", price: 130 },
  { id: 68, name: "Floor Cleaner", generalQuality: "Litre", price: 120 },
  { id: 69, name: "Phenyl", generalQuality: "Litre", price: 100 },
  { id: 70, name: "Dish Wash", generalQuality: "Litre", price: 90 },
  { id: 71, name: "Glass Cleaner", generalQuality: "Litre", price: 150 },
  { id: 72, name: "Mop Refill", generalQuality: "Kg", price: 200 },
  { id: 73, name: "Toilet Paper", generalQuality: "Kg", price: 120 },
  { id: 74, name: "Tissue Paper", generalQuality: "Kg", price: 80 },
  { id: 75, name: "Dustbin Bag", generalQuality: "Kg", price: 90 },
  { id: 76, name: "Plastic Wrap", generalQuality: "Kg", price: 100 },
  { id: 77, name: "Aluminum Foil", generalQuality: "Kg", price: 200 },
  { id: 78, name: "Matchbox", generalQuality: "Kg", price: 20 },
  { id: 79, name: "Candle", generalQuality: "Kg", price: 50 },
  { id: 80, name: "Gas Lighter", generalQuality: "Kg", price: 150 },
  { id: 81, name: "Battery", generalQuality: "Kg", price: 120 },
  { id: 82, name: "Chips", generalQuality: "Kg", price: 100 },
  { id: 83, name: "Namkeen", generalQuality: "Kg", price: 120 },
  { id: 84, name: "Chocolate", generalQuality: "Kg", price: 300 },
  { id: 85, name: "Cake", generalQuality: "Kg", price: 400 },
  { id: 86, name: "Cookies", generalQuality: "Kg", price: 180 },
  { id: 87, name: "Ice Cubes", generalQuality: "Kg", price: 20 },
  { id: 88, name: "Cold Pack", generalQuality: "Kg", price: 80 },
  { id: 89, name: "Lassi", generalQuality: "Litre", price: 60 },
  { id: 90, name: "Buttermilk", generalQuality: "Litre", price: 50 },
  { id: 91, name: "Pickle", generalQuality: "Kg", price: 200 },
  { id: 92, name: "Jam", generalQuality: "Kg", price: 180 },
  { id: 93, name: "Sauce", generalQuality: "Litre", price: 130 },
  { id: 94, name: "Ketchup", generalQuality: "Litre", price: 120 },
  { id: 95, name: "Vinegar", generalQuality: "Litre", price: 90 },
  { id: 96, name: "Soya Sauce", generalQuality: "Litre", price: 150 },
  { id: 97, name: "Green Chilli Sauce", generalQuality: "Litre", price: 140 },
  { id: 98, name: "Mustard Sauce", generalQuality: "Litre", price: 150 },
  { id: 99, name: "Mayonnaise", generalQuality: "Kg", price: 200 },
  { id: 100, name: "Cornflakes", generalQuality: "Kg", price: 250 }
];